#!/bin/bash

version=$(mvn help:evaluate -Dexpression=project.version | grep -v "Download" | grep -v "^\[")

version_next=$(eval echo "$(echo $version | sed 's/\(.*[^0-9]\{1,\}\)\([0-9]\{1,\}\)$/\1$((\2+1))/')")
mvn versions:set -DnewVersion="$version_next" -DgenerateBackupPoms=false

